# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4571cb60860a5ae231492df4c667f25e9c2fc2483e2169ffbbe93018e3f4247e6e20cd31291239d0c51cc9124015fa71b4f1dfaccd0730802225e62876150e26

test:
  secret_key_base: c73cf726d9b27524f5c48f29861efd070859030fb7ce39ac94599e3eed48a1612d11b7a85add8e5205606ad60b203b12fb317e3f39d6c98d4546004156e5f160

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
